# This is a basic workflow to help you get started with Actions

name: Release APK

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: "8.x"
          distribution: 'adopt'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      
      - name: Decoding key.properties
        uses: RollyPeres/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/android/key.properties
          encodedString: ${{ secrets.KEYPROP_PROD }}
      
      - name: Pub Get Packages
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --split-per-abi --release
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
