# This is a basic workflow to help you get started with Actions

name: Release APK

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*.*.*"
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  build:
    name: Update Anime Databases and Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y.%m.%d')"
          echo "::set-output name=short_date::$(date +'%y%m%d')"

      - name: Show Date
        run: echo "${{ steps.date.outputs.date }}(${{ steps.date.outputs.short_date }})"

      - name: Parse Tag and Version
        id: parse_version
        run: |
          sed -i -E "s/(version: [0-9]+\.[0-9]+\.)[0-9]+(\+)[0-9]+/\1${{ steps.date.outputs.short_date }}\2${{ github.run_number }}/" pubspec.yaml
          TAG_NAME=v`sed -n -E "s/version: ([0-9]+\.[0-9]+\.[0-9]+)\+[0-9]+/\1/p" pubspec.yaml`
          echo $TAG_NAME
          echo "::set-output name=tag_name::$TAG_NAME"
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Replace Cookies
        working-directory: ./anime_db
        run: |
          COOKIE=`echo "${{ secrets.BILI_COOKIE }}" | base64 --decode`
          sed -i -E "s/# COOKIE/${COOKIE//$'\n'/\\n}/" spy.py
      
      - name: Run Script
        working-directory: ./anime_db
        run: |
          pip install requests tqdm
          python spy.py

      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          add: '["./assets/anime.json", "./pubspec.yaml"]'
          branch: main
          default_author: user_info
          message: 'update data on ${{ steps.date.outputs.date }}'
          tag: '${{ steps.parse_version.outputs.tag_name }}'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: "8.x"
          distribution: 'adopt'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      
      - name: Decoding key.properties
        uses: RollyPeres/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/android/key.properties
          encodedString: ${{ secrets.KEYPROP_PROD }}
      
      - name: Pub Get Packages
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --split-per-abi --release
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/app/outputs/apk/release/*.apk"
          body: "Build ${{ steps.parse_version.outputs.tag_name }}"
          name: ${{ steps.parse_version.outputs.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
